Update#20221116
nnn-training/intro-curriculum-3026 pull request #148
Opened 2022-11-16 08:16 UTC by moesuke

関連：https://github.com/progedu/intro-2022-edition/pull/1666

2022-11-18 10:29 UTC, moesuke commented on views/posts.pug
> +      div(class=`${cardClass}`)
```suggestion
      div(class=cardClass)
```

2022-11-18 12:09 UTC, moesuke commented on views/posts.pug
> +        - cardClass = 'card my-3 bg-secondary text-white'
ここ治ってない！

2022-11-19 10:16 UTC, mikrogeophagus requested changes
### `lib/posts-handler.js`

`currentBodyClass`, `currentTextClass` が残っていましたので削除をお願いします。:bow:

```js
'use strict';
const pug = require('pug');
const Cookies = require('cookies');
const Post = require('./post');
const util = require('./handler-util');

const currentThemeKey = 'current_theme';
const dayjs = require('dayjs');
const utc = require('dayjs/plugin/utc');
const timezone = require('dayjs/plugin/timezone');
dayjs.extend(utc);
dayjs.extend(timezone);

async function handle(req, res) {
  const cookies = new Cookies(req, res);
  if(!cookies.get(currentThemeKey)) {
    const currentTheme = 'light';
    cookies.set(currentThemeKey,currentTheme);
  }
  switch (req.method) {
    case 'GET':
      res.writeHead(200, {
        'Content-Type': 'text/html; charset=utf-8'
      });
      const currentTheme = cookies.get(currentThemeKey);
      const posts = await Post.findAll({order:[['id', 'DESC']]});
      posts.forEach((post) => {
        post.content = post.content.replace(/\n/g, '<br>');
        post.formattedCreatedAt = dayjs(post.createdAt).tz('Asia/Tokyo').format('YYYY年MM月DD日 HH時mm分ss秒');
      });
      res.end(pug.renderFile('./views/posts.pug', { currentTheme, posts, user: req.user }));
      break;
    case 'POST':
      let body = '';
      req.on('data', (chunk) => {
        body += chunk;
      }).on('end', async () => {
        const params = new URLSearchParams(body);
        const content = params.get('content');
        console.info(`送信されました: ${content}`);
        await Post.create({
          content,
          postedBy: req.user
        });
        handleRedirectPosts(req, res);
      });
      break;
    default:
      util.handleBadRequest(req, res);
      break;
  }
}

function handleRedirectPosts(req, res) {
  res.writeHead(303, {
    'Location': '/posts'
  });
  res.end();
}

function handleDelete(req, res) {
  switch (req.method) {
    case 'POST':
      let body = '';
      req.on('data', (chunk) => {
        body += chunk;
      }).on('end', async () => {
        const params = new URLSearchParams(body);
        const id = params.get('id');
        const post = await Post.findByPk(id);
        if (req.user === post.postedBy || req.user === 'admin') {
          await post.destroy();
          console.info(
            `削除されました: user: ${req.user}, ` +
            `remoteAddress: ${req.socket.remoteAddress}, ` +
            `userAgent: ${req.headers['user-agent']} `
          );
          handleRedirectPosts(req, res);
        }
      });
      break;
    default:
      util.handleBadRequest(req, res);
      break;
  }
}

module.exports = {
  handle,
  handleDelete
};
```

2022-11-19 10:16 UTC, mikrogeophagus commented on views/posts.pug
> +        textarea(name="content" rows=4 class = currentTheme == 'light' ? "form-control":"form-control bg-secondary text-white")
`==` を `===` にする変更です。

```suggestion
        textarea(name="content" rows=4 class = currentTheme === 'light' ? "form-control" : "form-control bg-secondary text-white")
```

2022-11-21 01:34 UTC, merged